apiVersion: v1
kind: Service
metadata:
  name: angelorooms
  namespace: angelorooms
spec:
  selector:
    app: angelorooms
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
