apiVersion: v1
kind: Service
metadata:
  name: home-assistant-lb
  namespace: home-assistant
  labels:
    app: home-assistant
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    external-dns.alpha.kubernetes.io/hostname: home-assistant.lan.tapslab.com
spec:
  type: LoadBalancer
  selector:
    app: home-assistant
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
