apiVersion: v1
kind: Service
metadata:
  name: portfolio-site
  namespace: portfolio-site
spec:
  selector:
    app: portfolio-site
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080



